x-arcane:
  icon: https://shokoanime.com/images/common/shoko-icon.svg
  urls:
    - https://shokoanime.com/

version: 3
services:
  shoko_server:
    shm_size: 256m
    container_name: shoko-server
    image: ghcr.io/shokoanime/server:latest
    restart: unless-stopped
    ports:
      - 8111:8111
    volumes:
      - /root/etc/shoko:/home/shoko/.shoko
      - /mnt/cold/Anime:/mnt/anime